### ISSUE TITLE
Level: NaN

### ISSUE THREAD

**Issue by branjos** [blue1177/SkillClicker#2]
![image](https://user-images.githubusercontent.com/10274142/36498689-0fff9e94-170d-11e8-8191-a0bcfe1a9361.png)

Null level, should be 0

**Comment by branjos** [comment]
oh, this was after trying to load a game when one wasn't saved.

**Comment by blue1177** [comment]
Are you loading it off file://?

**Comment by blue1177** [comment]
side effect of local files, also fixed the links not having a blank target and needing to click back
